import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Frumatic Case App | Janberk Ucar</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="">
        <h1 className="text-2xl font-bold">Test</h1>
        <h1 className="test">Test</h1>
      </main>
      <footer className=""></footer>
    </div>
  );
};

export default Home;
