import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div className="">
      <Head>
        <title>Frumatic Case App | Janberk Ucar</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex flex-col">
        <h1 className="self-center text-3xl font-bold ">Frumatic Case App </h1>
      </main>
      <footer className=""></footer>
    </div>
  );
};

export default Home;
