import { GetServerSideProps } from "next";
import type { NextPage } from "next";
import Head from "next/head";
import { prisma } from "../db/client";
import { trpc } from "../utils/trpc";

const Index: NextPage = (props: any) => {
  const { data, isLoading } = trpc.useQuery(["hi"]);
  if (isLoading || !data) return <div>Loading...</div>;
  return (
    <div className="">
      <Head>
        <title>Frumatic Case App | Janberk Ucar</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex flex-col">
        <h1 className="self-center text-3xl font-bold ">Frumatic Case App </h1>
        <div className="flex flex-col text-center w-100 overflow-hidden">
          <h1>{data?.greeting}</h1>
          <code>{props.films}</code>
          <br />
          <code>{props.account}</code>
          <br />
          <code>{props.genres}</code>
        </div>
      </main>
      <footer className=""></footer>
    </div>
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  const filmData = await prisma.film.findMany();
  const accountData = await prisma.account.findMany();
  const genreData = await prisma.genre.findMany();

  return {
    props: {
      films: JSON.stringify(filmData),
      account: JSON.stringify(accountData),
      genres: JSON.stringify(genreData),
    },
  };
};

export default Index;
